db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost:1433;instanceName=NQKHANH;databaseName=DeThi03_24110251;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
db.username=sa
db.password=khanhnguyen1602
hikari.maximumPoolSize=10
hikari.minimumIdle=2
hikari.idleTimeout=30000
hikari.connectionTimeout=20000
